import assert from "node:assert/strict";
import test from "node:test";
import { ExecutionHandoffError, ExecutionHandoffState } from "../src/core/lifecycle.js";
type Action = { kind: "search"; query: string };
type Reason = "access_challenge" | "sign_in";
function fixture() { let now=1000; let id=0; return { state:new ExecutionHandoffState<Action,Reason>(()=>now,()=>`intervention-${++id}`), tick(){now+=1;} }; }
test("authority is exclusive and duplicate handoff does not replace the active intervention",()=>{ const {state}=fixture(); const first=state.begin({reason:"access_challenge",action:{kind:"search",query:"x"},resumePolicy:"replay_safe"}); const duplicate=state.begin({reason:"sign_in",resumePolicy:"never_replay"}); assert.equal(duplicate.id,first.id); assert.equal(state.getAuthority(),"none"); assert.throws(()=>state.assertAgentAuthority(),(e:unknown)=>e instanceof ExecutionHandoffError&&e.code==="AGENT_AUTHORITY_SUSPENDED"); const human=state.claimHuman(first.id); assert.equal(human.authority,"human"); assert.equal(state.getAuthority(),"human"); });
test("human completion fences stale resource state before agent resume",()=>{ const {state,tick}=fixture(); const started=state.begin({reason:"access_challenge",action:{kind:"search",query:"x"},resumePolicy:"replay_safe"}); state.claimHuman(started.id); tick(); const complete=state.markHumanComplete(started.id); assert.equal(complete.epoch,2); state.markVerified(started.id); const decision=state.resumeAgent(started.id); assert.equal(decision.epoch,2); assert.equal(decision.resumePolicy,"replay_safe"); assert.equal(state.getAuthority(),"agent"); });
test("stale intervention id and invalid transitions fail closed",()=>{ const {state}=fixture(); const started=state.begin({reason:"sign_in",resumePolicy:"never_replay"}); assert.throws(()=>state.claimHuman("stale"),(e:unknown)=>e instanceof ExecutionHandoffError&&e.code==="INTERVENTION_NOT_FOUND"); assert.throws(()=>state.markVerified(started.id),(e:unknown)=>e instanceof ExecutionHandoffError&&e.code==="INTERVENTION_STATE_CHANGED"); });
test("cancel advances epoch and restores agent authority",()=>{ const {state}=fixture(); const started=state.begin({reason:"access_challenge",resumePolicy:"never_replay"}); state.cancel(started.id); assert.equal(state.getResourceEpoch(),2); assert.equal(state.getAuthority(),"agent"); });
